repos:
  - repo: local
    hooks:
      - id: detekt
        name: detekt check
        description: Runs `detekt` on .kt files.
        language: script
        entry: scripts/detekt.sh
        types: [kotlin]